/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.1+134fc7b
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyHookCreateRequestRelationships } from './clockify-hook-create-request-relationships';
import { ClockifyHookAttributes } from './clockify-hook-attributes';


export interface ClockifyHookCreateRequestData { 
    /**
     * Resource type
     */
    readonly type: ClockifyHookCreateRequestData.TypeEnum;
    attributes: ClockifyHookAttributes;
    relationships: ClockifyHookCreateRequestRelationships;
}
export namespace ClockifyHookCreateRequestData {
    export type TypeEnum = 'ClockifyHook';
    export const TypeEnum = {
        ClockifyHook: 'ClockifyHook' as TypeEnum
    };
}


