/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationResource } from './organization-resource';
import { UserResource } from './user-resource';
import { UserAttributes } from './user-attributes';


/**
 * @type ClockifyHookCollectionResponseIncludedInner
 * @export
 */
export type ClockifyHookCollectionResponseIncludedInner = OrganizationResource | UserResource;

