/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifySettingsUpdateRequestRelationships } from './clockify-settings-update-request-relationships';
import { ClockifySettingsAttributes } from './clockify-settings-attributes';


export interface ClockifySettingsUpdateRequestData { 
    /**
     * Resource type
     */
    readonly type: ClockifySettingsUpdateRequestData.TypeEnum;
    attributes: ClockifySettingsAttributes;
    relationships: ClockifySettingsUpdateRequestRelationships;
}
export namespace ClockifySettingsUpdateRequestData {
    export type TypeEnum = 'ClockifySettings';
    export const TypeEnum = {
        ClockifySettings: 'ClockifySettings' as TypeEnum
    };
}


