/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyHookAttributes } from './clockify-hook-attributes';
import { JSONAPIErrorErrorsInnerLinks } from './jsonapi-error-errors-inner-links';
import { ClockifyHookResourceRelationships } from './clockify-hook-resource-relationships';


/**
 * The Clockify Hook Resource.
 */
export interface ClockifyHookResource { 
    /**
     * Resource identifier
     */
    readonly id: string;
    /**
     * Resource type
     */
    readonly type: ClockifyHookResource.TypeEnum;
    attributes: ClockifyHookAttributes;
    links?: JSONAPIErrorErrorsInnerLinks;
    relationships: ClockifyHookResourceRelationships;
}
export namespace ClockifyHookResource {
    export type TypeEnum = 'ClockifyHook';
    export const TypeEnum = {
        ClockifyHook: 'ClockifyHook' as TypeEnum
    };
}


