/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.2+e4727fd
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationRelationship } from './organization-relationship';
import { UserRelationship } from './user-relationship';


export interface ClockifyHookRelationships { 
    organization: OrganizationRelationship;
    user?: UserRelationship;
}

