/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifySettingsRelationship } from './clockify-settings-relationship';
import { OrganizationRelationship } from './organization-relationship';


export interface ClockifyServiceRelationships { 
    organization: OrganizationRelationship;
    settings: ClockifySettingsRelationship;
}

