/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.2+e4727fd
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyHookCollectionResponseIncludedInner } from './clockify-hook-collection-response-included-inner';
import { ClockifyHookCollectionResponseMeta } from './clockify-hook-collection-response-meta';
import { ClockifyHookResource } from './clockify-hook-resource';
import { ClockifyHookCollectionResponseLinks } from './clockify-hook-collection-response-links';


export interface ClockifyHookCollectionResponse { 
    links: ClockifyHookCollectionResponseLinks;
    meta: ClockifyHookCollectionResponseMeta;
    data: Set<ClockifyHookResource>;
    included?: Set<ClockifyHookCollectionResponseIncludedInner>;
}

