/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.1+134fc7b
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyServiceCreateRequestRelationships } from './clockify-service-create-request-relationships';
import { ClockifyServiceAttributes } from './clockify-service-attributes';


export interface ClockifyServiceCreateRequestData { 
    /**
     * Resource type
     */
    readonly type: ClockifyServiceCreateRequestData.TypeEnum;
    attributes: ClockifyServiceAttributes;
    relationships: ClockifyServiceCreateRequestRelationships;
}
export namespace ClockifyServiceCreateRequestData {
    export type TypeEnum = 'ClockifyService';
    export const TypeEnum = {
        ClockifyService: 'ClockifyService' as TypeEnum
    };
}


