/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.1.0+e417cb8
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyUsersCollectionResponseMeta } from './clockify-users-collection-response-meta';
import { ClockifyUserResource } from './clockify-user-resource';
import { UserResource } from './user-resource';
import { ClockifyUsersCollectionResponseLinks } from './clockify-users-collection-response-links';


export interface ClockifyUsersCollectionResponse { 
    links: ClockifyUsersCollectionResponseLinks;
    meta: ClockifyUsersCollectionResponseMeta;
    data?: Array<ClockifyUserResource>;
    included?: Array<UserResource>;
}

