/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyServiceUpdateRequestRelationships } from './clockify-service-update-request-relationships';
import { ClockifyServiceAttributes } from './clockify-service-attributes';


export interface ClockifyServiceUpdateRequestData { 
    /**
     * Resource type
     */
    readonly type: ClockifyServiceUpdateRequestData.TypeEnum;
    attributes: ClockifyServiceAttributes;
    relationships: ClockifyServiceUpdateRequestRelationships;
}
export namespace ClockifyServiceUpdateRequestData {
    export type TypeEnum = 'ClockifyService';
    export const TypeEnum = {
        ClockifyService: 'ClockifyService' as TypeEnum
    };
}


