/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.2+e4727fd
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyUserRelationships } from './clockify-user-relationships';
import { ClockifyUserAttributes } from './clockify-user-attributes';


/**
 * The Clockify User Resource.
 */
export interface ClockifyUserResource { 
    /**
     * Resource identifier
     */
    readonly id: string;
    /**
     * Resource type
     */
    readonly type: ClockifyUserResource.TypeEnum;
    attributes: ClockifyUserAttributes;
    relationships: ClockifyUserRelationships;
}
export namespace ClockifyUserResource {
    export type TypeEnum = 'ClockifyUser';
    export const TypeEnum = {
        ClockifyUser: 'ClockifyUser' as TypeEnum
    };
}


