/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MOCOServiceResourceRelationships } from './moco-service-resource-relationships';
import { MOCOServiceAttributes } from './moco-service-attributes';


export interface CreateMocoServiceRequestData { 
    /**
     * Resource type
     */
    readonly type: CreateMocoServiceRequestData.TypeEnum;
    attributes: MOCOServiceAttributes;
    relationships: MOCOServiceResourceRelationships;
}
export namespace CreateMocoServiceRequestData {
    export type TypeEnum = 'MocoService';
    export const TypeEnum = {
        MocoService: 'MocoService' as TypeEnum
    };
}


