/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.1+134fc7b
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAccessTokenErrorResponse { 
    type: string;
    title: string;
    status: CreateAccessTokenErrorResponse.StatusEnum;
    detail: string;
}
export namespace CreateAccessTokenErrorResponse {
    export type StatusEnum = 400;
    export const StatusEnum = {
        NUMBER_400: 400 as StatusEnum
    };
}


