/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MOCOSettingsAttributes } from './moco-settings-attributes';
import { MOCOSettingsResourceRelationships } from './moco-settings-resource-relationships';


export interface CreateMocoSettingsRequestData { 
    /**
     * Resource type
     */
    readonly type: CreateMocoSettingsRequestData.TypeEnum;
    attributes: MOCOSettingsAttributes;
    relationships: MOCOSettingsResourceRelationships;
}
export namespace CreateMocoSettingsRequestData {
    export type TypeEnum = 'MocoSettings';
    export const TypeEnum = {
        MocoSettings: 'MocoSettings' as TypeEnum
    };
}


