/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecuteClockifyWebhookRequestTimeInterval } from './execute-clockify-webhook-request-time-interval';
import { ExecuteClockifyWebhookRequestTagsInner } from './execute-clockify-webhook-request-tags-inner';
import { ExecuteClockifyWebhookRequestProject } from './execute-clockify-webhook-request-project';
import { ExecuteClockifyWebhookRequestUser } from './execute-clockify-webhook-request-user';


export interface ExecuteClockifyWebhookRequest { 
    id: string;
    description: string;
    timeInterval: ExecuteClockifyWebhookRequestTimeInterval;
    tags: Array<ExecuteClockifyWebhookRequestTagsInner>;
    project?: ExecuteClockifyWebhookRequestProject;
    task?: ExecuteClockifyWebhookRequestTagsInner;
    user: ExecuteClockifyWebhookRequestUser;
}

