/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetClockifyHookCollection200ResponseIncludedInner } from './get-clockify-hook-collection200-response-included-inner';
import { ClockifyHookResource } from './clockify-hook-resource';
import { GetClockifyHookCollection200ResponseLinks } from './get-clockify-hook-collection200-response-links';
import { GetClockifyHookCollection200ResponseMeta } from './get-clockify-hook-collection200-response-meta';


export interface GetClockifyHookCollection200Response { 
    links: GetClockifyHookCollection200ResponseLinks;
    meta: GetClockifyHookCollection200ResponseMeta;
    data: Set<ClockifyHookResource>;
    included?: Set<GetClockifyHookCollection200ResponseIncludedInner>;
}

