/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MOCOServiceResource } from './moco-service-resource';
import { GetMocoServiceCollection200ResponseIncludedInner } from './get-moco-service-collection200-response-included-inner';


export interface GetMocoService200Response { 
    data: MOCOServiceResource;
    included?: Set<GetMocoServiceCollection200ResponseIncludedInner>;
}

