/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetEntryPoint200ResponseLinks } from './get-entry-point200-response-links';
import { Null } from './null';
import { JSONAPIServerDescription } from './jsonapi-server-description';


export interface GetEntryPoint200Response { 
    meta: Null;
    jsonapi: JSONAPIServerDescription;
    links: GetEntryPoint200ResponseLinks;
}

