/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationResource } from './organization-resource';
import { GetClockifyHookCollection200ResponseLinks } from './get-clockify-hook-collection200-response-links';
import { MOCOSettingsResource } from './moco-settings-resource';
import { GetClockifyHookCollection200ResponseMeta } from './get-clockify-hook-collection200-response-meta';


export interface GetMocoSettingsCollection200Response { 
    links: GetClockifyHookCollection200ResponseLinks;
    meta: GetClockifyHookCollection200ResponseMeta;
    data: Set<MOCOSettingsResource>;
    included?: Set<OrganizationResource>;
}

