/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyUserResource } from './clockify-user-resource';
import { UserResource } from './user-resource';


export interface GetClockifyUser204Response { 
    data: ClockifyUserResource;
    included?: Set<UserResource>;
}

