/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JSONAPIErrorErrorsInner } from './jsonapi-error-errors-inner';
import { JSONAPIServerDescription } from './jsonapi-server-description';
import { JSONAPIErrorLinks } from './jsonapi-error-links';


/**
 * Error objects provide additional information about problems encountered while performing an operation. Error objects **MUST** be returned as an array keyed by `errors` in the top level of a JSON:API document. 
 */
export interface JSONAPIError { 
    errors: Array<JSONAPIErrorErrorsInner>;
    jsonapi?: JSONAPIServerDescription;
    links?: JSONAPIErrorLinks;
}

