/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.2+e4727fd
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JsonApiErrorItemSource } from './json-api-error-item-source';
import { JsonApiLink } from './json-api-link';


export interface JsonApiErrorItem { 
    /**
     * A unique identifier for this particular occurence of the problem.
     */
    id?: string;
    links?: { [key: string]: JsonApiLink; };
    /**
     * The HTTP status code applicable to this problem, expressed as a string value.
     */
    status?: string;
    /**
     * An application-specific error code, expressed as a string value.
     */
    code?: string;
    /**
     * A short human-readable summary of the problem. It **SHOULD NOT** change from occurence to occurence of the problem, except for purposes of localization.
     */
    title?: string;
    /**
     * A human-readable explanation specific to this occurence of the problem.
     */
    detail?: string;
    source?: JsonApiErrorItemSource;
    /**
     * A meta object containing non-standard meta-information about the error.
     */
    meta?: object;
}

