/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JsonApiServerDescriptionMeta } from './json-api-server-description-meta';


/**
 * An object describing the server implementation
 */
export interface JsonApiServerDescription { 
    /**
     * The JSON:API version supported by the server.
     */
    version?: string;
    meta?: JsonApiServerDescriptionMeta;
}

