/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JSONAPILinkOneOf } from './jsonapi-link-one-of';


/**
 * A link **MUST** be represented as either: * a string containing the URL of the link * or `link object` 
 */
/**
 * @type JSONAPILink
 * A link **MUST** be represented as either: * a string containing the URL of the link * or `link object` 
 * @export
 */
export type JSONAPILink = JSONAPILinkOneOf | string;

