/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JSONAPIErrorErrorsInnerSource } from './jsonapi-error-errors-inner-source';
import { JSONAPIErrorErrorsInnerLinks } from './jsonapi-error-errors-inner-links';


export interface JSONAPIErrorErrorsInner { 
    /**
     * A unique identifier for this particular occurence of the problem.
     */
    id?: string;
    links?: JSONAPIErrorErrorsInnerLinks;
    /**
     * The HTTP status code applicable to this problem, expressed as a string value.
     */
    status?: string;
    /**
     * An application-specific error code, expressed as a string value.
     */
    code?: string;
    /**
     * A short human-readable summary of the problem. It **SHOULD NOT** change from occurence to occurence of the problem, except for purposes of localization.
     */
    title?: string;
    /**
     * A human-readable explanation specific to this occurence of the problem.
     */
    detail?: string;
    source?: JSONAPIErrorErrorsInnerSource;
    /**
     * A meta object containing non-standard meta-information about the error.
     */
    meta?: object;
}

