/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.2+e4727fd
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The JSON:API metadata of the server.
 */
export interface JsonApiServerDescriptionMeta { 
    /**
     * The revision of the application behind this API.
     */
    appRevision: string;
    /**
     * The version of the application behind this API.
     */
    appVersion: string;
}

