/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.0+914aca3
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MOCOUserWebhookRequest } from './moco-user-webhook-request';
import { MOCOTaskWebhookRequest } from './moco-task-webhook-request';
import { MOCOProjectWebhookRequest } from './moco-project-webhook-request';
import { MOCOProjectWebhookRequestContract } from './moco-project-webhook-request-contract';
import { MOCOProjectWebhookRequestCustomer } from './moco-project-webhook-request-customer';
import { MOCOCompanyWebhookRequest } from './moco-company-webhook-request';
import { MOCOTaskWebhookRequestProject } from './moco-task-webhook-request-project';


/**
 * @type MOCOWebhookRequest
 * @export
 */
export type MOCOWebhookRequest = MOCOCompanyWebhookRequest | MOCOProjectWebhookRequest | MOCOTaskWebhookRequest | MOCOUserWebhookRequest;

