/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.1+134fc7b
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MocoHookUpdateRequestRelationships } from './moco-hook-update-request-relationships';
import { MocoHookAttributes } from './moco-hook-attributes';


export interface MocoHookUpdateRequestData { 
    /**
     * Resource type
     */
    readonly type: MocoHookUpdateRequestData.TypeEnum;
    attributes: MocoHookAttributes;
    relationships: MocoHookUpdateRequestRelationships;
}
export namespace MocoHookUpdateRequestData {
    export type TypeEnum = 'MocoHook';
    export const TypeEnum = {
        MocoHook: 'MocoHook' as TypeEnum
    };
}


