/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.1+134fc7b
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MocoServiceAttributes } from './moco-service-attributes';
import { MocoServiceRelationships } from './moco-service-relationships';


/**
 * The MOCO Service Resource.
 */
export interface MocoServiceResource { 
    /**
     * Resource identifier
     */
    readonly id: string;
    /**
     * Resource type
     */
    readonly type: MocoServiceResource.TypeEnum;
    attributes: MocoServiceAttributes;
    relationships: MocoServiceRelationships;
}
export namespace MocoServiceResource {
    export type TypeEnum = 'MocoService';
    export const TypeEnum = {
        MocoService: 'MocoService' as TypeEnum
    };
}


