/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.1+134fc7b
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The MOCO Settings Attributes.
 */
export interface MocoSettingsAttributes { 
    /**
     * MOCO service identifier
     */
    readonly _id?: string;
    /**
     * MOCO API host
     */
    host: string;
}

