/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.0+914aca3
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The MOCO Hook Attributes.
 */
export interface MocoHookAttributes { 
    /**
     * MOCO hook identifier
     */
    readonly _id?: string;
    /**
     * Clockify hook status
     */
    status: MocoHookAttributes.StatusEnum;
    /**
     * Clockify signature
     */
    signatureKey: string;
    target: MocoHookAttributes.TargetEnum;
}
export namespace MocoHookAttributes {
    export type StatusEnum = 'ENABLED' | 'DISABLED';
    export const StatusEnum = {
        Enabled: 'ENABLED' as StatusEnum,
        Disabled: 'DISABLED' as StatusEnum
    };
    export type TargetEnum = 'COMPANY' | 'PROJECT' | 'TASK' | 'USER';
    export const TargetEnum = {
        Company: 'COMPANY' as TargetEnum,
        Project: 'PROJECT' as TargetEnum,
        Task: 'TASK' as TargetEnum,
        User: 'USER' as TargetEnum
    };
}


