/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 2.0.0+0fee254
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MocoSettingsRelationshipData } from './moco-settings-relationship-data';


/**
 * The MOCO Settings Relationship.
 */
export interface MocoSettingsRelationship { 
    data: MocoSettingsRelationshipData;
}

