/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.0+914aca3
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MOCOProjectWebhookRequestContract } from './moco-project-webhook-request-contract';
import { MOCOProjectWebhookRequestCustomer } from './moco-project-webhook-request-customer';


/**
 * Project Request Object
 */
export interface MOCOProjectWebhookRequest { 
    id: number;
    name: string;
    customer: MOCOProjectWebhookRequestCustomer;
    contracts: Set<MOCOProjectWebhookRequestContract>;
}

