/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.3+af59792
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationAttributes } from './organization-attributes';


/**
 * The Organization Resource.
 */
export interface OrganizationResource { 
    /**
     * Resource identifier
     */
    readonly id: string;
    /**
     * Resource type
     */
    readonly type: OrganizationResource.TypeEnum;
    attributes: OrganizationAttributes;
}
export namespace OrganizationResource {
    export type TypeEnum = 'Organization';
    export const TypeEnum = {
        Organization: 'Organization' as TypeEnum
    };
}


