/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.1.1+134fc7b
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizationCollectionResponseMeta } from './organization-collection-response-meta';
import { OrganizationResource } from './organization-resource';
import { OrganizationCollectionResponseLinks } from './organization-collection-response-links';


export interface OrganizationCollectionResponse { 
    links: OrganizationCollectionResponseLinks;
    meta: OrganizationCollectionResponseMeta;
    data: Set<OrganizationResource>;
}

