/**
 * skriptfabrik API
 * This is the specification for the skriptfabrik API.
 *
 * The version of the OpenAPI document: 1.0.0+65bfafc
 * Contact: info@skriptfabrik.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClockifyUserResourceRelationships } from './clockify-user-resource-relationships';
import { ClockifyUserAttributes } from './clockify-user-attributes';


export interface UpdateClockifyUserRequestData { 
    /**
     * Resource type
     */
    readonly type: UpdateClockifyUserRequestData.TypeEnum;
    attributes?: ClockifyUserAttributes;
    relationships: ClockifyUserResourceRelationships;
}
export namespace UpdateClockifyUserRequestData {
    export type TypeEnum = 'ClockifyUser';
    export const TypeEnum = {
        ClockifyUser: 'ClockifyUser' as TypeEnum
    };
}


