version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    reviewers:
      - 'skriptfabrik/api-client-maintainers'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'npm'
    directory: '/'
    ignore:
      - dependency-name: '@types/*'
    reviewers:
      - 'skriptfabrik/api-client-maintainers'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'
