export * from './admin.service';
import { AdminService } from './admin.service';
export * from './authorization.service';
import { AuthorizationService } from './authorization.service';
export * from './clockify-hook.service';
import { ClockifyHookService } from './clockify-hook.service';
export * from './clockify-service.service';
import { ClockifyServiceService } from './clockify-service.service';
export * from './clockify-settings.service';
import { ClockifySettingsService } from './clockify-settings.service';
export * from './clockify-user.service';
import { ClockifyUserService } from './clockify-user.service';
export * from './moco-hook.service';
import { MOCOHookService } from './moco-hook.service';
export * from './moco-service.service';
import { MOCOServiceService } from './moco-service.service';
export * from './moco-settings.service';
import { MOCOSettingsService } from './moco-settings.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './webhooks.service';
import { WebhooksService } from './webhooks.service';
export const APIS = [AdminService, AuthorizationService, ClockifyHookService, ClockifyServiceService, ClockifySettingsService, ClockifyUserService, MOCOHookService, MOCOServiceService, MOCOSettingsService, OrganizationService, UserService, WebhooksService];
